# Generated by Django 3.2.5 on 2021-07-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainScreen1Model',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.FloatField()),
                ('photo', models.ImageField(upload_to='employee_images/')),
            ],
        ),
    ]
