# Generated by Django 3.0.5 on 2021-07-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplainScreen1Model',
        ),
    ]
