# Generated by Django 3.0.5 on 2021-07-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_complainscreen1model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UserComplainScreen1',
        ),
    ]
