# Generated by Django 3.0.5 on 2021-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210719_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('Very Bad', 'Very Bad'), ('Not Satisfied', 'Not Satisfied'), ('Satisfied', 'Satisfied'), ('Very Good', 'Very Good')], max_length=100)),
            ],
        ),
    ]
