# Generated by Django 3.0.5 on 2021-07-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_messagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackModel',
            new_name='UserComplainScreen3',
        ),
        migrations.RenameModel(
            old_name='MessageModel',
            new_name='UserComplainScreen4',
        ),
    ]
