# Generated by Django 3.0.5 on 2021-07-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210719_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterShelterScreen2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaded_area', models.FloatField()),
                ('non_shaded_area', models.FloatField()),
                ('hand_pump', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fodder', models.FloatField()),
                ('space_keeping_fodder', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('space_green_fodder', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('dump_area', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('electricity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10)),
                ('no_of_fans', models.FloatField()),
                ('no_of_light', models.FloatField()),
            ],
        ),
    ]
