# Generated by Django 3.0.5 on 2021-07-19 10:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_registershelterscreen2model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_backup', multiselectfield.db.fields.MultiSelectField(choices=[('Invertor', 'Invertor'), ('Solar Plant', 'Solar Plant'), ('Global Gas', 'Global Gas'), ('Generator', 'Generator')], max_length=41)),
                ('source_of_income', multiselectfield.db.fields.MultiSelectField(choices=[('Milk Sell', 'Milk Sell'), ('Cow Dung Sell', 'Cow Dung Sell'), ('Compost Sell', 'Compost Sell'), ('Urine Sell', 'Urine Sell'), ('By Products', 'By Products')], max_length=100)),
                ('veterinary_doctor_visit', multiselectfield.db.fields.MultiSelectField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Yearly')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('availability_of_First_aid', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='', max_length=100)),
            ],
        ),
    ]
