# Generated by Django 3.0.5 on 2021-07-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_facilitiesmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilitiesModel',
            new_name='RegisterShelterScreen3Model',
        ),
    ]
